# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:

- script: |
    az deployment group create -f ./main.bicep -g kevin-bicep-demo --parameters location=$(region) name=$(StoAccountName)
  displayName: 'Bicep - Deploy Storage Account'
