trigger:
- main

pool:
 vmImage: windows-latest

variables:
  DevReleaseTemplate: './azure-pipelines-release-devtest.yml'
  ProdReleaseTemplate: './azure-pipelines-release-prod.yml'

stages:
- stage: 'DevTest'
  displayName: 'Deploy to DevTest environment'
  jobs:
  - template: ${{ variables.DevReleaseTemplate }}
    parameters:
      variableGroup: 'Dev-Variables'
      environment: 'DevTest'

- stage: 'Prod'
  displayName: 'Deploy to Prod environment'
  jobs:
  - template: ${{ variables.ProdReleaseTemplate }}
    parameters:
      variableGroup: 'Prod-Variables'
      environment: 'Prod'