parameters:
- name: variableGroup
  type: string

- name: environment
  type: string

jobs:
  - deployment: DeploySolution
    displayName: 'Deploy Resources'
    variables:
    - group: ${{ parameters.variableGroup }} # points to variable group in Azure DevOps
    environment: ${{ parameters.environment }} # points to environments in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
         
          - task: AzureCLI@2
            displayName: 'Deploy Bicep File'
            inputs:
             azureSubscription: 'KevinCurran-InternalSub'
             scriptType: 'ps'
             scriptLocation: 'inlineScript'
             inlineScript: 'az deployment sub create -f $(Agent.BuildDirectory)/s/BicepFiles/main.bicep -l $(region) --parameters RGname=$(RGname) region=$(region) StoAccountName=$(StoAccountName) ContainerName=$(ContainerName) sku=$(sku) WorkspaceName=$(WorkspaceName)'    