trigger:
- main

pool:
 vmImage: windows-latest

stages:
- stage: 'DevTest'
  displayName: 'Deploy to DevTest environment'
  jobs:
  - deployment: DeploySolution
    displayName: 'Deploy Resources'
    variables:
    - group: 'Dev-Variables' # points to variable group in Azure DevOps
    environment: $(EnvironmentName) # points to environment in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
         
          - task: AzureCLI@2
            displayName: 'Deploy Bicep File'
            inputs:
             azureSubscription: $(ServiceConnectionName)
             scriptType: 'ps'
             scriptLocation: 'inlineScript'
             inlineScript: 'az deployment sub create -f $(Agent.BuildDirectory)/s/BicepFiles/main.bicep -l $(region) --parameters RGname=$(RGname) region=$(region) StoAccountName=$(StoAccountName) ContainerName=$(ContainerName) sku=$(sku) WorkspaceName=$(WorkspaceName)'  

- stage: 'Prod'
  displayName: 'Deploy to Prod environment'
  jobs:
  - deployment: DeploySolution
    displayName: 'Deploy Resources'
    variables:
    - group: 'Prod-Variables' # points to variable group in Azure DevOps
    environment: $(EnvironmentName) # points to environment in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
         
          - task: AzureCLI@2
            displayName: 'Deploy Bicep File'
            inputs:
             azureSubscription: $(ServiceConnectionName)
             scriptType: 'ps'
             scriptLocation: 'inlineScript'
             inlineScript: 'az deployment sub create -f $(Agent.BuildDirectory)/s/BicepFiles/main.bicep -l $(region) --parameters RGname=$(RGname) region=$(region) StoAccountName=$(StoAccountName) ContainerName=$(ContainerName) sku=$(sku) WorkspaceName=$(WorkspaceName)'  