parameters:
- name: variableGroup
  type: string

- name: environment
  type: string

jobs:
  - deployment: DeploySolution
    displayName: 'Create RG & Deploy Storage Account'
    variables:
    - group: ${{ parameters.variableGroup }} # points to variable group in Azure DevOps
    environment: ${{ parameters.environment }} # points to environments in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: 'Upgrade AzCLI'
            inputs:
             azureSubscription: 'DevTest-ServiceConnection'
             scriptType: 'ps'
             scriptLocation: 'inlineScript'
             inlineScript: 'az upgrade --yes'

          - task: AzureCLI@2
            displayName: 'Create RG'
            inputs:
             azureSubscription: 'DevTest-ServiceConnection'
             scriptType: 'ps'
             scriptLocation: 'inlineScript'
             inlineScript: 'az group create --name $(RGname) --location $(region)'
         
          - task: AzureCLI@2
            displayName: 'Deploy Bicep File'
            inputs:
             azureSubscription: 'DevTest-ServiceConnection'
             scriptType: 'ps'
             scriptLocation: 'inlineScript'
             inlineScript: 'az deployment group create -f $(Agent.BuildDirectory)/BicepFiles/StoAcct.bicep -g $(RGname) --parameters region=$(region) StoAccountName=$(StoAccountName) ContainerName=$(ContainerName) sku=$(sku)'    