# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription (7e453d73-03a4-4e0f-be6d-85545b0e91d5)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment group create -f ./BicepFiles/main.bicep -g $RGname --parameters region=$region StoAccountName=$StoAccountName ContainerName=$ContainerName sku=$sku'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
