# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'Kevin Self-Hosted'

variables:
  DevReleaseTemplate: './azure-pipelines-release-devtest.yml'
  ProdReleaseTemplate: './azure-pipelines-release-prod.yml'

stages:
- stage: 'Checkout Source'
  displayName: 'Checkout source code to build agent' 
  steps:
  - checkout: self

- stage: 'DevTest'
  displayName: 'Deploy to DevTest environment'
  jobs:
  - template: ${{ variables.DevReleaseTemplate }}
    parameters:
      variableGroup: 'Dev-Variables'
      environment: 'DevTest'

- stage: 'Prod'
  displayName: 'Deploy to Prod environment'
  jobs:
  - template: ${{ variables.ProdReleaseTemplate }}
    parameters:
      variableGroup: 'Prod-Variables'
      environment: 'Prod'
