name: Deploy to Dev

# Controls when the action will run. 
on:
  # Triggers the workflow on push, but only for the dev branch
  push:
    branches:
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: ubuntu-latest
    environment: Dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2           

      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDS_DEV }}
    
      - name: Deploy Bicep with AzCLI
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            az deployment sub create -f $GITHUB_WORKSPACE/BicepFiles/main.bicep -l SouthCentralUS \
            --parameters $GITHUB_WORKSPACE/Parameters/azure-parameters-dev.json --parameters VMadminPassword=${{ secrets.VMADMINPASSWORD }}